#ifndef S_ERROR_H
# define S_ERROR_H

# define ERROR_OPEN -1
# define ERROR_MALLOC 2
# define ERROR_CARDINAL 3
# define ERROR_FLOOR 4
# define ERROR_MISSING_INFO 5
# define ERROR_MAP 6
# define ERROR_MAPMISSING 7
# define ERROR_INVALID_RGB 8
# define ERROR_WRONG_NBR_ARG 9
# define ERROR_MLX 10
# define ERROR_MAP_DIM 11
# define ERROR_INVALID_ID 12
# define ERROR_CARDINAL_DUP_MISS 13
# define ERROR_WRONG_CARDINAL 14
# define ERROR_PLAYER 15
# define ERROR_NOT_SURROUNDED 16
# define ERROR_WRONG_EXTENSION 17
# define ERROR_NO_EXTENSION 18
# define ERROR_FILE 19

#endif
